"""Pure, fixed-point core for pathwise research PnL."""

from .contracts import (
    CENTICENTS_PER_DOLLAR,
    MICRODOLLARS_PER_CENT,
    MICRODOLLARS_PER_CENTICENT,
    MONEY_SCALE_E6,
    PRICE_SCALE_E4,
    QUANTITY_SCALE_E4,
    CashFlow,
    CashFlowKind,
    ClosureState,
    ContractError,
    FillPurpose,
    FillRecord,
    LiquidityRole,
    Outcome,
    PathSpec,
    Side,
    canonical_sha256,
    exact_trade_notional_cc,
    exact_trade_notional_e6,
)
from .fees import (
    AmbiguousFeeRule,
    BalanceRounding,
    FeeAssessment,
    FeePrecision,
    FeeRule,
    FeeSchedule,
    FeeTruthUnavailable,
    apply_balance_rounding,
)
from .latency import (
    LatencyPath,
    LatencyReceipt,
    LatencySample,
    LatencyTruthUnavailable,
    MeasuredLatencyProfile,
)
from .ledger import (
    IncompletePnL,
    LedgerInvariantError,
    PnLLedger,
    PnLResult,
)
from .risk import (
    RiskInvariantError,
    RiskLedger,
    RiskLimitExceeded,
    RiskLimits,
    RiskRequest,
)
from .terminal import (
    SettlementRecord,
    SettlementStatus,
    TerminalDecision,
    classify_settlement,
)

__all__ = [
    "AmbiguousFeeRule",
    "BalanceRounding",
    "CENTICENTS_PER_DOLLAR",
    "CashFlow",
    "CashFlowKind",
    "ClosureState",
    "ContractError",
    "FeeAssessment",
    "FeePrecision",
    "FeeRule",
    "FeeSchedule",
    "FeeTruthUnavailable",
    "FillPurpose",
    "FillRecord",
    "IncompletePnL",
    "LatencyPath",
    "LatencyReceipt",
    "LatencySample",
    "LatencyTruthUnavailable",
    "LedgerInvariantError",
    "LiquidityRole",
    "MICRODOLLARS_PER_CENT",
    "MICRODOLLARS_PER_CENTICENT",
    "MONEY_SCALE_E6",
    "MeasuredLatencyProfile",
    "Outcome",
    "PRICE_SCALE_E4",
    "PathSpec",
    "PnLLedger",
    "PnLResult",
    "QUANTITY_SCALE_E4",
    "RiskInvariantError",
    "RiskLedger",
    "RiskLimitExceeded",
    "RiskLimits",
    "RiskRequest",
    "SettlementRecord",
    "SettlementStatus",
    "Side",
    "TerminalDecision",
    "apply_balance_rounding",
    "canonical_sha256",
    "classify_settlement",
    "exact_trade_notional_cc",
    "exact_trade_notional_e6",
]
